language: node_js
node_js:
  - "8"
before_install:
  - npm config set @fortawesome:registry https://npm.fontawesome.com/$FONTAWESOME_NPM_TOKEN
script:
  - npm run build
after_success:
  - "zip -r carehr.zip *.html bundle.js favicon.png img"
  - "curl -F 'data=@carehr.zip' -H 'X-Key: '$DEPLOY_KEY -H 'X-ExtractTo: .' https://carehr.nl/deploy/"
